name: Push to Replicate

on:
  workflow_dispatch:
    inputs:
      model_name:
        description: 'Например: panpetos/guillotine-inpaint'
        required: true

jobs:
  push_to_replicate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Cog
        uses: replicate/setup-cog@v2
        with:
          token: ${{ secrets.REPLICATE_CLI_AUTH_TOKEN }}

      - name: Push to Replicate
        run: cog push r8.im/${{ inputs.model_name }}
