name: Push to Replicate

on:
  workflow_dispatch:
    inputs:
      model_name:
        description: 'Например: panpetos/guillotine-inpaint'
        required: true

jobs:
  push_to_replicate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: replicate/setup-cog@v2
        with:
          token: ${{ secrets.REPLICATE_CLI_AUTH_TOKEN }}
      - run: cog push r8.im/${{ inputs.model_name }}
